// GENERATED by @edgedb/generate v0.4.1

import * as $ from "../reflection.mjs";
import * as _ from "../imports.mjs";
const Role = $.makeType(_.spec, "0b351395-8f35-11ee-b6a4-e17f6c50b040", _.syntax.literal);

const Status = $.makeType(_.spec, "0c5f6ead-8f35-11ee-a19a-4748037a0c38", _.syntax.literal);

const $HasTimestamp = $.makeType(_.spec, "0b328302-8f35-11ee-aaa2-a947beb26d2d", _.syntax.literal);

const HasTimestamp= _.syntax.$PathNode($.$toSet($HasTimestamp, $.Cardinality.Many), null);

const $Client = $.makeType(_.spec, "0c5f7ce6-8f35-11ee-ade8-59caa8569b1d", _.syntax.literal);

const Client= _.syntax.$PathNode($.$toSet($Client, $.Cardinality.Many), null);

const $Comment = $.makeType(_.spec, "0b33e352-8f35-11ee-8fab-b18783d0c1ff", _.syntax.literal);

const Comment= _.syntax.$PathNode($.$toSet($Comment, $.Cardinality.Many), null);

const $Cost = $.makeType(_.spec, "2cfdf989-8f35-11ee-b939-95f1a6be72a6", _.syntax.literal);

const Cost= _.syntax.$PathNode($.$toSet($Cost, $.Cardinality.Many), null);

const $Job = $.makeType(_.spec, "0cb074eb-8f35-11ee-9674-81d70601cc3d", _.syntax.literal);

const Job= _.syntax.$PathNode($.$toSet($Job, $.Cardinality.Many), null);

const $Payment = $.makeType(_.spec, "2d0547d6-8f35-11ee-8e05-b1e2222e76c4", _.syntax.literal);

const Payment= _.syntax.$PathNode($.$toSet($Payment, $.Cardinality.Many), null);

const $Post = $.makeType(_.spec, "0b3a14a1-8f35-11ee-a696-fbb4eaaef0d8", _.syntax.literal);

const Post= _.syntax.$PathNode($.$toSet($Post, $.Cardinality.Many), null);

const $Tag = $.makeType(_.spec, "0b38bf21-8f35-11ee-b1f9-7dbc6dac5e93", _.syntax.literal);

const Tag= _.syntax.$PathNode($.$toSet($Tag, $.Cardinality.Many), null);

const $User = $.makeType(_.spec, "0b35201c-8f35-11ee-a8ff-c996171cd09e", _.syntax.literal);

const User= _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);



export { Role, Status, $HasTimestamp, HasTimestamp, $Client, Client, $Comment, Comment, $Cost, Cost, $Job, Job, $Payment, Payment, $Post, Post, $Tag, Tag, $User, User };

const __defaultExports = {
  "Role": Role,
  "Status": Status,
  "HasTimestamp": HasTimestamp,
  "Client": Client,
  "Comment": Comment,
  "Cost": Cost,
  "Job": Job,
  "Payment": Payment,
  "Post": Post,
  "Tag": Tag,
  "User": User
};
export default __defaultExports;
